
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvmjgcoepabfedwlvbcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2bWpnY29lcGFiZmVkd2x2YmNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMjczNzcsImV4cCI6MjA2MjcwMzM3N30.j9hFj36VwYck6jONHQRdP_Dg9-LMbcHWghbq2I3Q4ug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Verify Supabase Connection
export const checkSupabaseConnection = async (): Promise<boolean> => {
  try {
    const { data, error } = await supabase.from('clients').select('count').limit(1);
    return !error;
  } catch (e) {
    console.error("Supabase connection error:", e);
    return false;
  }
};
